import type { Property } from './types'

/**
 * Immobili di ESEMPIO per il concept. Indirizzi, prezzi, quote e testi sono
 * verosimili ma inventati: non vanno pubblicati. Il tono dei testi
 * ("Perché ci piace", "Cose da sapere") è quello da mantenere.
 */
export const properties: Property[] = [
  {
    slug: 'dorsoduro-ultimo-piano-altana-zattere',
    ref: 'IMM-DD-101',
    title: 'Ultimo piano con altana sulle Zattere',
    zone: 'dorsoduro',
    microZone: 'Zattere',
    type: 'attico',
    availability: 'disponibile',
    price: 1_250_000,
    area: { commercial: 138, net: 118, outdoor: 22 },
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    floor: { label: 'Terzo e ultimo piano', level: 3, buildingFloors: 3, lift: false },
    entranceElevationCm: 128,
    energy: { class: 'D', ipe: 148 },
    heating: 'Autonomo a metano, radiatori in ghisa',
    built: 'XVII secolo',
    renovated: 2019,
    condition: 'ristrutturato',
    exposure: 'Sud, sud-ovest',
    listedBuilding: false,
    condoFees: 120,
    availableFrom: 'Libero al rogito',
    features: ['altana', 'vista-canale', 'piano-alto'],
    hook: 'Da qui la Giudecca sembra a un passo, e il tramonto entra in casa ogni sera.',
    summary:
      'Ultimo piano di 138 m² con altana di 22 m² sul canale della Giudecca. Tre camere, due bagni, ristrutturato nel 2019.',
    description: [
      'Si sale per tre rampe di un palazzo seicentesco affacciato sulle Zattere, la fondamenta più luminosa di Venezia. La porta si apre su un soggiorno di oltre trenta metri con tre finestre a sud: il canale della Giudecca riempie la stanza di luce per quasi tutto il giorno.',
      'La ristrutturazione del 2019 ha rispettato ciò che contava: i pavimenti alla veneziana sono stati restaurati, le travi del soffitto lasciate a vista, gli impianti rifatti per intero. La cucina è separata dal soggiorno, come si preferisce a Venezia, e guarda sul rio laterale.',
      'La zona notte ha tre camere e due bagni finestrati. Dal disimpegno una scala in legno porta all’altana, ventidue metri di tavolato sopra i tetti: a ovest il porto, a sud il Redentore, a est la Salute.',
    ],
    whyWeLikeIt: [
      'È raro trovare un’altana regolare e accatastata con questa vista: la maggior parte non lo è.',
      'La luce: tre finestre a sud sul canale più largo della città, senza palazzi di fronte.',
      'Le Zattere sono ancora un luogo di residenti: forno, farmacia e supermercato a pochi minuti.',
    ],
    thingsToKnow: [
      {
        kind: 'acqua',
        title: 'Acqua alta',
        text: 'Ingresso a +128 cm. Con le maree sopra questa quota la fondamenta davanti al portone si bagna; il MOSE protegge la città dagli eventi eccezionali. L’appartamento non è mai interessato.',
      },
      {
        kind: 'accesso',
        title: 'Scale',
        text: 'Tre rampe senza ascensore; l’ultima, verso la zona notte, è ripida. Per i mobili grandi si usa il trasporto via acqua.',
      },
      {
        kind: 'lavori',
        title: 'Facciata',
        text: 'Il condominio ha deliberato il restauro della facciata per il 2027. Quota stimata per l’appartamento: 14.000 euro, già considerata nel prezzo.',
      },
      {
        kind: 'vincoli',
        title: 'Documenti',
        text: 'Altana autorizzata e accatastata, conformità urbanistica verificata dal nostro tecnico. Documenti disponibili prima della visita.',
      },
    ],
    vaporetto: { stop: 'Zattere', lines: ['2', '5.1', '5.2'], minutes: 3 },
    proximity: [
      { label: 'Gallerie dell’Accademia', minutes: 7, mode: 'a piedi' },
      { label: 'Supermercato', minutes: 4, mode: 'a piedi' },
      { label: 'Piazzale Roma', minutes: 18, mode: 'a piedi' },
      { label: 'Piazza San Marco', minutes: 10, mode: 'in vaporetto' },
    ],
    images: ['soggiorno-luce', 'soggiorno-alto', 'cucina-bianca', 'camera-lino', 'bagno-pietra', 'venezia-luce', 'interno-dettaglio'],
    plan: [
      {
        label: 'Terzo piano',
        rooms: [
          { name: 'Soggiorno', x: 0, y: 0, w: 6.4, h: 5.2 },
          { name: 'Cucina', x: 6.4, y: 0, w: 3.4, h: 3.2 },
          { name: 'Camera', x: 9.8, y: 0, w: 3.4, h: 5.2 },
          { name: 'Disimpegno', x: 6.4, y: 3.2, w: 3.4, h: 2 },
          { name: 'Camera', x: 0, y: 5.2, w: 3.6, h: 3.4 },
          { name: 'Camera', x: 3.6, y: 5.2, w: 2.8, h: 3.4 },
          { name: 'Bagno', x: 6.4, y: 5.2, w: 2.4, h: 3.4 },
          { name: 'Bagno', x: 8.8, y: 5.2, w: 2, h: 3.4 },
          { name: 'Ingresso', x: 10.8, y: 5.2, w: 2.4, h: 3.4 },
        ],
      },
      { label: 'Altana', rooms: [{ name: 'Altana', x: 0, y: 0, w: 5.5, h: 4, outdoor: true }] },
    ],
    featured: true,
    publishedAt: '2026-09-12',
  },
  {
    slug: 'cannaregio-casa-corte-misericordia',
    ref: 'IMM-CN-102',
    title: 'Casa con corte privata alla Misericordia',
    zone: 'cannaregio',
    microZone: 'Misericordia',
    type: 'casa',
    availability: 'disponibile',
    price: 980_000,
    area: { commercial: 172, net: 148, outdoor: 38 },
    rooms: 6,
    bedrooms: 3,
    bathrooms: 2,
    floor: { label: 'Terra e primo piano', level: 0, buildingFloors: 2, lift: false },
    entranceElevationCm: 132,
    energy: { class: 'E', ipe: 186 },
    heating: 'Autonomo a metano, a pavimento al piano terra',
    built: 'XVIII secolo',
    renovated: 2016,
    condition: 'buono',
    exposure: 'Est, ovest',
    listedBuilding: false,
    condoFees: 0,
    availableFrom: 'Da concordare, entro sei mesi',
    features: ['corte', 'accesso-acqua'],
    hook: 'Una corte tutta vostra, a trenta passi dalla fondamenta più viva di Cannaregio.',
    summary:
      'Casa indipendente su due livelli con corte privata di 38 m² e porta d’acqua. Tre camere, a due passi dalla Misericordia.',
    description: [
      'Dalla calle si entra in una corte lastricata in trachite, con un pozzo in pietra d’Istria e un fico che d’estate fa ombra a mezza facciata. La casa occupa due piani ed è indipendente: niente condominio, niente scale in comune.',
      'Al piano terra, rialzato, ci sono il soggiorno, una cucina abitabile che si apre sulla corte e un bagno di servizio. Il riscaldamento a pavimento, installato nel 2016, rende questo piano confortevole anche d’inverno.',
      'Al primo piano tre camere, uno studio e un bagno con finestra sul rio. Una porta d’acqua sul retro dà sul rio della Sensa: comoda per le consegne, preziosa il giorno del trasloco.',
    ],
    whyWeLikeIt: [
      'Una casa indipendente con corte a Cannaregio è una rarità: ne vediamo una o due all’anno.',
      'La Misericordia è la Venezia dei veneziani: bacari, botteghe, bambini in bicicletta sulle fondamenta.',
      'La stazione è a quattordici minuti a piedi: comodissima per chi lavora in terraferma.',
    ],
    thingsToKnow: [
      {
        kind: 'acqua',
        title: 'Acqua alta',
        text: 'Piano terra rialzato a +142 cm. La corte si bagna con maree sopra i 125 cm: nel 2016 sono state installate paratie e una pompa di drenaggio, entrambe funzionanti.',
      },
      {
        kind: 'impianti',
        title: 'Impianti',
        text: 'Impianto elettrico rifatto nel 2016, caldaia a condensazione del 2021. Serramenti in legno da manutenere nei prossimi anni.',
      },
      {
        kind: 'accesso',
        title: 'Porta d’acqua',
        text: 'Utilizzabile con barche piccole. Non è incluso un posto barca: la concessione va richiesta al Comune.',
      },
      {
        kind: 'costi',
        title: 'Spese',
        text: 'Nessuna spesa condominiale. Manutenzione della corte e del pozzo a carico del proprietario.',
      },
    ],
    vaporetto: { stop: 'Madonna dell’Orto', lines: ['4.1', '4.2', '5.1', '5.2'], minutes: 5 },
    proximity: [
      { label: 'Stazione ferroviaria', minutes: 14, mode: 'a piedi' },
      { label: 'Mercato di Rio Terà San Leonardo', minutes: 7, mode: 'a piedi' },
      { label: 'Scuola primaria', minutes: 5, mode: 'a piedi' },
      { label: 'Fondamente Nove', minutes: 9, mode: 'a piedi' },
    ],
    images: ['casa-esterno', 'soggiorno-caldo', 'cucina-isola', 'camera-calma', 'giardino-verde', 'venezia-rio'],
    plan: [
      {
        label: 'Piano terra',
        rooms: [
          { name: 'Ingresso', x: 0, y: 0, w: 2.4, h: 3 },
          { name: 'Soggiorno', x: 2.4, y: 0, w: 6, h: 5 },
          { name: 'Cucina', x: 8.4, y: 0, w: 4, h: 5 },
          { name: 'Bagno', x: 0, y: 3, w: 2.4, h: 2 },
          { name: 'Corte', x: 0, y: 5, w: 9.5, h: 4, outdoor: true },
        ],
      },
      {
        label: 'Primo piano',
        rooms: [
          { name: 'Camera', x: 0, y: 0, w: 4.4, h: 4.2 },
          { name: 'Camera', x: 4.4, y: 0, w: 3.8, h: 4.2 },
          { name: 'Camera', x: 8.2, y: 0, w: 4.2, h: 4.2 },
          { name: 'Bagno', x: 0, y: 4.2, w: 3, h: 2.4 },
          { name: 'Studio', x: 3, y: 4.2, w: 5.2, h: 2.4 },
          { name: 'Disimpegno', x: 8.2, y: 4.2, w: 4.2, h: 2.4 },
        ],
      },
    ],
    featured: true,
    publishedAt: '2026-09-02',
  },
  {
    slug: 'san-marco-piano-nobile-canal-grande',
    ref: 'IMM-SM-103',
    title: 'Piano nobile sul Canal Grande',
    zone: 'san-marco',
    microZone: 'San Samuele',
    type: 'piano-nobile',
    availability: 'disponibile',
    price: null,
    area: { commercial: 265, net: 232 },
    rooms: 8,
    bedrooms: 4,
    bathrooms: 3,
    floor: { label: 'Primo piano nobile', level: 1, buildingFloors: 4, lift: true },
    entranceElevationCm: 118,
    energy: { class: 'G', ipe: 246 },
    heating: 'Centralizzato con contabilizzazione, radiante nelle zone di servizio',
    built: 'XV secolo, facciata gotica',
    renovated: 2008,
    condition: 'buono',
    exposure: 'Est sul Canal Grande, ovest sulla corte',
    listedBuilding: true,
    condoFees: 650,
    availableFrom: 'Libero al rogito',
    features: ['vista-canale', 'accesso-acqua', 'ascensore'],
    hook: 'Il portego corre da una facciata all’altra: da un lato il Canal Grande, dall’altro la corte del palazzo.',
    summary:
      'Piano nobile di 265 m² in un palazzo gotico sul Canal Grande, con portego passante, quattro camere e accesso acqueo.',
    description: [
      'Un palazzo del Quattrocento a pochi passi da Campo San Samuele. Il piano nobile si sviluppa, come vuole la tradizione veneziana, attorno a un portego di oltre sessanta metri quadrati: la quadrifora gotica sul Canal Grande da un lato, le finestre sulla corte interna dall’altro.',
      'Ai lati del portego si aprono il salotto con soffitto a travi decorate, la biblioteca, la cucina e quattro camere, di cui una padronale con bagno. I pavimenti in terrazzo originale sono stati restaurati nel 2008 insieme agli impianti.',
      'Il palazzo dispone di ascensore, di portineria e di una riva d’acqua con cavana condominiale: si arriva in taxi acqueo fin dentro l’androne.',
    ],
    whyWeLikeIt: [
      'Un piano nobile con portego passante e quadrifora sul Canal Grande: sono poche decine in tutta la città.',
      'L’ascensore, in un palazzo vincolato, è un piccolo miracolo burocratico già compiuto.',
      'San Samuele è il lato quieto del sestiere: Palazzo Grassi a due passi, la folla di San Marco lontana.',
    ],
    thingsToKnow: [
      {
        kind: 'vincoli',
        title: 'Vincolo della Soprintendenza',
        text: 'Palazzo vincolato: ogni intervento interno va autorizzato. I tempi medi per un’autorizzazione sono di tre-sei mesi.',
      },
      {
        kind: 'acqua',
        title: 'Acqua alta',
        text: 'L’androne è a +118 cm e si bagna con maree sopra questa quota; la riva d’acqua ha paratie. L’appartamento è a oltre cinque metri sul medio mare.',
      },
      {
        kind: 'costi',
        title: 'Spese condominiali',
        text: '650 euro al mese: comprendono portineria, ascensore, pulizie e manutenzione della riva e della cavana.',
      },
      {
        kind: 'impianti',
        title: 'Classe energetica G',
        text: 'Serramenti storici, non sostituibili ma migliorabili con vetri interni reversibili: abbiamo un preventivo indicativo.',
      },
    ],
    vaporetto: { stop: 'San Samuele', lines: ['2'], minutes: 2 },
    proximity: [
      { label: 'Campo Santo Stefano', minutes: 4, mode: 'a piedi' },
      { label: 'Teatro La Fenice', minutes: 8, mode: 'a piedi' },
      { label: 'Piazza San Marco', minutes: 10, mode: 'a piedi' },
      { label: 'Piazzale Roma', minutes: 20, mode: 'in vaporetto' },
    ],
    images: ['soggiorno-ampio', 'venezia-canal-grande', 'interno-sera', 'camera-lino', 'soggiorno-quiete', 'bagno-pietra', 'interno-dettaglio'],
    plan: [
      {
        label: 'Piano nobile',
        rooms: [
          { name: 'Portego', x: 7.5, y: 0, w: 5.5, h: 11.6 },
          { name: 'Salotto', x: 0, y: 0, w: 7.5, h: 4.8 },
          { name: 'Camera', x: 0, y: 4.8, w: 7.5, h: 3.4 },
          { name: 'Cucina', x: 0, y: 8.2, w: 7.5, h: 3.4 },
          { name: 'Camera', x: 13, y: 0, w: 7, h: 4.8 },
          { name: 'Bagno', x: 13, y: 4.8, w: 3, h: 3.4 },
          { name: 'Camera', x: 16, y: 4.8, w: 4, h: 3.4 },
          { name: 'Camera', x: 13, y: 8.2, w: 3.8, h: 3.4 },
          { name: 'Bagno', x: 16.8, y: 8.2, w: 3.2, h: 1.7 },
          { name: 'Bagno', x: 16.8, y: 9.9, w: 3.2, h: 1.7 },
        ],
      },
    ],
    featured: true,
    publishedAt: '2026-08-28',
  },
  {
    slug: 'castello-bilocale-via-garibaldi',
    ref: 'IMM-CS-104',
    title: 'Bilocale luminoso vicino a Via Garibaldi',
    zone: 'castello',
    microZone: 'Via Garibaldi',
    type: 'appartamento',
    availability: 'disponibile',
    price: 285_000,
    area: { commercial: 62, net: 52 },
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    floor: { label: 'Secondo piano', level: 2, buildingFloors: 3, lift: false },
    entranceElevationCm: 124,
    energy: { class: 'E', ipe: 172 },
    heating: 'Autonomo a metano',
    built: 'XIX secolo',
    renovated: 2012,
    condition: 'buono',
    exposure: 'Sud',
    listedBuilding: false,
    condoFees: 45,
    availableFrom: 'Libero al rogito',
    features: ['vista-canale'],
    hook: 'Piccolo, ben fatto, in una delle strade più vere della città.',
    summary:
      'Bilocale di 62 m² al secondo piano, esposto a sud su un rio tranquillo, a due minuti da Via Garibaldi e dai Giardini.',
    description: [
      'Un secondo piano esposto a sud, con due finestre su un rio dove passano più barche da lavoro che gondole. Il soggiorno ha l’angolo cottura in muratura e un tavolo per sei; la camera è abbastanza grande per un letto matrimoniale e un armadio a tutta parete.',
      'La casa è stata sistemata nel 2012 e tenuta con cura. È pronta da abitare; col tempo cucina e bagno meriteranno una rinfrescata.',
    ],
    whyWeLikeIt: [
      'Via Garibaldi è una delle ultime strade di Venezia con il mercato, il forno e le sedie fuori dalle porte.',
      'L’esposizione a sud e l’affaccio sul rio lo rendono molto più luminoso della media dei bilocali.',
      'Un ingresso serio nel mercato veneziano: prima casa, oppure pied-à-terre.',
    ],
    thingsToKnow: [
      {
        kind: 'acqua',
        title: 'Acqua alta',
        text: 'Ingresso a +124 cm: la calle si bagna con maree sopra questa quota, l’appartamento no.',
      },
      {
        kind: 'accesso',
        title: 'Scale e traslochi',
        text: 'Due rampe strette: per i mobili grandi serve il trasporto via acqua dalla finestra, come spesso accade a Venezia.',
      },
      {
        kind: 'costi',
        title: 'Locazioni',
        text: 'Adatto anche all’affitto di medio periodo. Per le locazioni turistiche va verificato il regolamento comunale in vigore.',
      },
    ],
    vaporetto: { stop: 'Giardini', lines: ['1', '4.1', '4.2', '5.1', '5.2'], minutes: 4 },
    proximity: [
      { label: 'Mercato di Via Garibaldi', minutes: 2, mode: 'a piedi' },
      { label: 'Arsenale', minutes: 6, mode: 'a piedi' },
      { label: 'Ospedale civile', minutes: 18, mode: 'a piedi' },
      { label: 'Piazza San Marco', minutes: 20, mode: 'a piedi' },
    ],
    images: ['interno-arioso', 'cucina-bianca', 'camera-calma', 'venezia-sera'],
    plan: [
      {
        label: 'Secondo piano',
        rooms: [
          { name: 'Soggiorno e cucina', x: 0, y: 0, w: 5.6, h: 5.2 },
          { name: 'Camera', x: 5.6, y: 0, w: 4.4, h: 3.4 },
          { name: 'Bagno', x: 5.6, y: 3.4, w: 2.4, h: 1.8 },
          { name: 'Ingresso', x: 8, y: 3.4, w: 2, h: 1.8 },
        ],
      },
    ],
    publishedAt: '2026-09-18',
  },
  {
    slug: 'giudecca-loft-sulla-laguna',
    ref: 'IMM-GD-105',
    title: 'Loft sull’acqua alla Giudecca',
    zone: 'giudecca',
    microZone: 'Molino Stucky',
    type: 'loft',
    availability: 'disponibile',
    price: 890_000,
    area: { commercial: 152, net: 131, outdoor: 16 },
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    floor: { label: 'Secondo piano', level: 2, buildingFloors: 4, lift: true },
    entranceElevationCm: 142,
    energy: { class: 'B', ipe: 62 },
    heating: 'Pompa di calore, pavimento radiante',
    built: 'Ex magazzino industriale, 1920',
    renovated: 2021,
    condition: 'nuovo',
    exposure: 'Nord, ovest sul canale',
    listedBuilding: false,
    condoFees: 210,
    availableFrom: 'Libero al rogito',
    features: ['vista-laguna', 'terrazza', 'ascensore'],
    hook: 'Quattro metri e mezzo di soffitto, travi originali e la laguna al posto del muro.',
    summary:
      'Loft di 152 m² in un ex magazzino del 1920, con terrazza sul canale, ascensore e classe B. Due camere, due bagni.',
    description: [
      'Un magazzino degli anni Venti, trasformato nel 2021 con un progetto che ha tenuto la struttura in vista: capriate in legno, muri in mattoni, soffitti di quattro metri e mezzo. L’open space di oltre settanta metri guarda sul canale della Giudecca attraverso quattro grandi vetrate.',
      'La zona notte è separata da una parete attrezzata in rovere: due camere, ciascuna con il proprio bagno. Dalla zona giorno si esce su una terrazza di sedici metri, a pelo del canale.',
      'Pompa di calore, pavimento radiante e serramenti a taglio termico: una casa che a Venezia consuma come una nuova costruzione.',
    ],
    whyWeLikeIt: [
      'Metrature e altezze così, nel centro storico, esistono quasi solo alla Giudecca.',
      'La classe B: bollette da casa nuova in un edificio con cento anni di storia.',
      'Da qui si vede Venezia intera. E la sera, tornando in vaporetto, si capisce perché.',
    ],
    thingsToKnow: [
      {
        kind: 'accesso',
        title: 'Vaporetto',
        text: 'La fermata Palanca è a quattro minuti. Le corse notturne sono meno frequenti: da mettere in conto se si esce spesso la sera.',
      },
      {
        kind: 'acqua',
        title: 'Acqua alta',
        text: 'Ingresso a +142 cm, tra i più protetti della zona. Il complesso ha un sistema di paratie condominiale.',
      },
      {
        kind: 'costi',
        title: 'Spese condominiali',
        text: '210 euro al mese: comprendono ascensore, pulizie e manutenzione del pontile comune.',
      },
    ],
    vaporetto: { stop: 'Palanca', lines: ['2', '4.1', '4.2'], minutes: 4 },
    proximity: [
      { label: 'Zattere', minutes: 5, mode: 'in vaporetto' },
      { label: 'Supermercato', minutes: 5, mode: 'a piedi' },
      { label: 'Chiesa del Redentore', minutes: 8, mode: 'a piedi' },
      { label: 'Piazza San Marco', minutes: 12, mode: 'in vaporetto' },
    ],
    images: ['interno-studio', 'soggiorno-ampio', 'cucina-isola', 'camera-lino', 'bagno-pietra', 'venezia-sera'],
    plan: [
      {
        label: 'Secondo piano',
        rooms: [
          { name: 'Soggiorno e cucina', x: 0, y: 0, w: 9, h: 8.2 },
          { name: 'Camera', x: 9, y: 0, w: 4, h: 4.4 },
          { name: 'Bagno', x: 13, y: 0, w: 3, h: 4.4 },
          { name: 'Camera', x: 9, y: 4.4, w: 4, h: 3.8 },
          { name: 'Bagno', x: 13, y: 4.4, w: 3, h: 3.8 },
          { name: 'Terrazza', x: 0, y: 8.2, w: 6.4, h: 2.5, outdoor: true },
        ],
      },
    ],
    featured: true,
    publishedAt: '2026-08-20',
  },
  {
    slug: 'lido-villa-liberty-giardino',
    ref: 'IMM-LD-106',
    title: 'Villa liberty con giardino al Lido',
    zone: 'lido',
    microZone: 'Quattro Fontane',
    type: 'villa',
    availability: 'disponibile',
    price: 1_650_000,
    area: { commercial: 310, net: 268, outdoor: 620 },
    rooms: 9,
    bedrooms: 5,
    bathrooms: 3,
    floor: { label: 'Tre livelli e seminterrato', level: 0, buildingFloors: 3, lift: false },
    entranceElevationCm: 185,
    energy: { class: 'F', ipe: 212 },
    heating: 'Autonomo a metano, radiatori',
    built: '1912',
    renovated: 1998,
    condition: 'buono',
    exposure: 'Quattro lati, giardino a sud',
    listedBuilding: true,
    condoFees: 0,
    availableFrom: 'Da concordare',
    features: ['giardino', 'posto-auto', 'terrazza'],
    hook: 'Un giardino di seicento metri, i pini marittimi e il mare a sei minuti in bicicletta.',
    summary:
      'Villa liberty del 1912 di 310 m² su tre livelli, con giardino di 620 m², veranda e posto auto. Cinque camere.',
    description: [
      'Una villa del 1912 in una delle strade più belle del Lido, tra ville d’epoca e giardini. Il cancello in ferro battuto apre su un giardino di seicentoventi metri con pini marittimi, una magnolia e un vialetto in ghiaia fino al posto auto.',
      'Il piano terra ha un salone con camino, la sala da pranzo con le vetrate originali e una veranda sul giardino; la cucina è stata rifatta nel 1998. Al primo piano tre camere e due bagni; al secondo, sotto il tetto, altre due camere e uno studio con terrazzino.',
      'La casa ha bisogno di un aggiornamento degli impianti e dei bagni. La struttura, i decori liberty e i serramenti originali sono in buono stato.',
    ],
    whyWeLikeIt: [
      'Il Lido è l’unico posto di Venezia dove si hanno insieme giardino, auto e mare.',
      'I decori originali, dalle vetrate ai pavimenti, sono sopravvissuti quasi intatti. Non capita spesso.',
      'Per una famiglia è una scelta di vita: scuole, sport e spiaggia a pochi minuti, San Marco a quindici di vaporetto.',
    ],
    thingsToKnow: [
      {
        kind: 'vincoli',
        title: 'Villa vincolata',
        text: 'Facciate, serramenti e decori vanno conservati. Gli interventi interni si concordano con la Soprintendenza.',
      },
      {
        kind: 'lavori',
        title: 'Impianti e bagni',
        text: 'Da aggiornare. Preventivo indicativo del nostro tecnico: 180.000–220.000 euro, a seconda delle finiture.',
      },
      {
        kind: 'acqua',
        title: 'Seminterrato',
        text: 'Nessuna esposizione all’acqua alta. Il seminterrato ha avuto infiltrazioni nel 2019, risolte con un’impermeabilizzazione documentata.',
      },
      {
        kind: 'costi',
        title: 'Giardino',
        text: 'Manutenzione stimata intorno ai 3.000 euro l’anno.',
      },
    ],
    vaporetto: { stop: 'Lido S.M. Elisabetta', lines: ['1', '5.1', '5.2', '6'], minutes: 12 },
    proximity: [
      { label: 'Spiaggia', minutes: 6, mode: 'in bici' },
      { label: 'Gran Viale', minutes: 8, mode: 'a piedi' },
      { label: 'Scuola primaria', minutes: 5, mode: 'a piedi' },
      { label: 'Piazza San Marco', minutes: 15, mode: 'in vaporetto' },
    ],
    images: ['villa-esterno', 'casa-esterno', 'soggiorno-quiete', 'cucina-bianca', 'camera-calma', 'giardino-verde'],
    plan: [
      {
        label: 'Piano terra',
        rooms: [
          { name: 'Salone', x: 0, y: 0, w: 7, h: 6 },
          { name: 'Sala da pranzo', x: 7, y: 0, w: 5, h: 6 },
          { name: 'Cucina', x: 12, y: 0, w: 4.5, h: 4 },
          { name: 'Bagno', x: 12, y: 4, w: 2, h: 2 },
          { name: 'Ingresso', x: 14, y: 4, w: 2.5, h: 2 },
          { name: 'Veranda', x: 0, y: 6, w: 7, h: 2.5, outdoor: true },
        ],
      },
      {
        label: 'Primo piano',
        rooms: [
          { name: 'Camera', x: 0, y: 0, w: 5, h: 4.5 },
          { name: 'Camera', x: 5, y: 0, w: 5, h: 4.5 },
          { name: 'Camera', x: 10, y: 0, w: 6.5, h: 4.5 },
          { name: 'Bagno', x: 0, y: 4.5, w: 3, h: 3 },
          { name: 'Bagno', x: 3, y: 4.5, w: 3, h: 3 },
          { name: 'Disimpegno', x: 6, y: 4.5, w: 10.5, h: 3 },
        ],
      },
      {
        label: 'Secondo piano',
        rooms: [
          { name: 'Camera', x: 0, y: 0, w: 5, h: 4 },
          { name: 'Camera', x: 5, y: 0, w: 5, h: 4 },
          { name: 'Studio', x: 10, y: 0, w: 4, h: 4 },
          { name: 'Terrazzino', x: 10, y: 4, w: 4, h: 1.8, outdoor: true },
        ],
      },
    ],
    publishedAt: '2026-07-30',
  },
  {
    slug: 'san-polo-trilocale-rialto',
    ref: 'IMM-SP-107',
    title: 'Trilocale a due passi dal mercato di Rialto',
    zone: 'san-polo',
    microZone: 'Rialto',
    type: 'appartamento',
    availability: 'disponibile',
    price: 520_000,
    area: { commercial: 94, net: 81 },
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    floor: { label: 'Primo piano', level: 1, buildingFloors: 4, lift: false },
    entranceElevationCm: 108,
    energy: { class: 'E', ipe: 176 },
    heating: 'Autonomo a metano',
    built: 'XVI secolo',
    renovated: 2010,
    condition: 'buono',
    exposure: 'Est',
    listedBuilding: false,
    condoFees: 90,
    availableFrom: 'Libero al rogito',
    features: [],
    hook: 'La spesa si fa in Pescheria, il caffè al banco sotto casa: la Venezia di ogni giorno.',
    summary:
      'Trilocale di 94 m² al primo piano, due camere, a due minuti dal mercato di Rialto. Soffitti a travi, pavimenti in legno.',
    description: [
      'Un primo piano in un palazzo del Cinquecento, in una calle tra l’Erbaria e Campo San Polo. Il soggiorno ha due finestre a est e un soffitto a travi dipinte; la cucina, separata, è piccola ma ben organizzata.',
      'Due camere, un bagno finestrato e uno studio che può diventare cabina armadio o camera per gli ospiti. La casa è stata sistemata nel 2010: pavimenti in rovere, impianti a norma, infissi in legno con vetrocamera.',
    ],
    whyWeLikeIt: [
      'Vivere accanto al mercato di Rialto significa fare la spesa come si faceva cinquecento anni fa.',
      'Il primo piano mette al riparo dall’acqua alta senza costringere a salire troppe scale.',
      'Centralissimo, eppure la sera la calle torna silenziosa.',
    ],
    thingsToKnow: [
      {
        kind: 'acqua',
        title: 'Acqua alta',
        text: 'Ingresso a +108 cm, una quota bassa: l’androne si bagna alcune volte l’anno con le maree tra 110 e 120 cm. L’appartamento non è interessato.',
      },
      {
        kind: 'accesso',
        title: 'La calle',
        text: 'Molto frequentata nelle ore di mercato: vivace di mattina, tranquilla la sera.',
      },
      {
        kind: 'lavori',
        title: 'Tetto',
        text: 'Tetto rifatto nel 2022, spesa già interamente saldata dal venditore.',
      },
    ],
    vaporetto: { stop: 'Rialto Mercato', lines: ['1'], minutes: 3 },
    proximity: [
      { label: 'Mercato di Rialto', minutes: 2, mode: 'a piedi' },
      { label: 'Campo San Polo', minutes: 6, mode: 'a piedi' },
      { label: 'Basilica dei Frari', minutes: 10, mode: 'a piedi' },
      { label: 'Piazzale Roma', minutes: 15, mode: 'a piedi' },
    ],
    images: ['soggiorno-caldo', 'cucina-bianca', 'camera-lino', 'venezia-canal-grande'],
    plan: [
      {
        label: 'Primo piano',
        rooms: [
          { name: 'Soggiorno', x: 0, y: 0, w: 5.4, h: 4.2 },
          { name: 'Cucina', x: 0, y: 4.2, w: 3.2, h: 2.6 },
          { name: 'Ingresso', x: 3.2, y: 4.2, w: 2.2, h: 2.6 },
          { name: 'Camera', x: 5.4, y: 0, w: 3.6, h: 4.2 },
          { name: 'Camera', x: 9, y: 0, w: 3, h: 4.2 },
          { name: 'Bagno', x: 5.4, y: 4.2, w: 3, h: 2.6 },
          { name: 'Studio', x: 8.4, y: 4.2, w: 3.6, h: 2.6 },
        ],
      },
    ],
    publishedAt: '2026-09-08',
  },
  {
    slug: 'santa-croce-campo-san-giacomo',
    ref: 'IMM-SC-108',
    title: 'Appartamento su Campo San Giacomo dall’Orio',
    zone: 'santa-croce',
    microZone: 'San Giacomo dall’Orio',
    type: 'appartamento',
    availability: 'disponibile',
    price: 640_000,
    area: { commercial: 112, net: 97 },
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    floor: { label: 'Secondo piano', level: 2, buildingFloors: 3, lift: false },
    entranceElevationCm: 126,
    energy: { class: 'D', ipe: 139 },
    heating: 'Autonomo, pompa di calore ibrida',
    built: 'XVIII secolo',
    renovated: 2018,
    condition: 'ristrutturato',
    exposure: 'Sud, est sul campo',
    listedBuilding: false,
    condoFees: 70,
    availableFrom: 'Libero al rogito',
    features: [],
    hook: 'Tre finestre sul campo dove i veneziani portano ancora i bambini a giocare.',
    summary:
      'Appartamento di 112 m² ristrutturato nel 2018, con tre finestre su Campo San Giacomo dall’Orio. Due camere, due bagni.',
    description: [
      'Il soggiorno guarda il campo attraverso tre finestre alte: gli alberi, la chiesa romanica, le panchine all’ombra. È uno dei campi più amati dai residenti, e si capisce subito perché.',
      'La ristrutturazione del 2018 ha ridisegnato la pianta: cucina separata, due camere sul lato della corte interna, due bagni, uno studio. Pavimenti in seminato veneziano nel soggiorno, rovere nella zona notte.',
    ],
    whyWeLikeIt: [
      'Il campo è il vero soggiorno di casa: dal mattino alla sera, cambia luce e cambia gente.',
      'Piazzale Roma è a otto minuti: perfetto per chi lavora in terraferma o usa l’auto nei fine settimana.',
      'Una ristrutturazione recente e fatta bene: nessun lavoro da mettere in conto.',
    ],
    thingsToKnow: [
      {
        kind: 'accesso',
        title: 'Rumore',
        text: 'D’estate il campo è animato fino a sera. Le camere danno sulla corte interna, silenziosa.',
      },
      {
        kind: 'acqua',
        title: 'Acqua alta',
        text: 'Ingresso a +126 cm: il campo si bagna solo con le maree più alte.',
      },
      {
        kind: 'impianti',
        title: 'Impianti',
        text: 'Pompa di calore ibrida del 2018, con manutenzione annuale documentata.',
      },
    ],
    vaporetto: { stop: 'Riva de Biasio', lines: ['1'], minutes: 5 },
    proximity: [
      { label: 'Supermercato', minutes: 3, mode: 'a piedi' },
      { label: 'Piazzale Roma', minutes: 8, mode: 'a piedi' },
      { label: 'Stazione ferroviaria', minutes: 9, mode: 'a piedi' },
      { label: 'Rialto', minutes: 12, mode: 'a piedi' },
    ],
    images: ['soggiorno-alto', 'interno-pietra', 'cucina-bianca', 'camera-calma', 'bagno-pietra', 'venezia-rio'],
    plan: [
      {
        label: 'Secondo piano',
        rooms: [
          { name: 'Soggiorno', x: 0, y: 0, w: 6, h: 4.6 },
          { name: 'Cucina', x: 6, y: 0, w: 3, h: 4.6 },
          { name: 'Camera', x: 9, y: 0, w: 3.4, h: 4.6 },
          { name: 'Camera', x: 0, y: 4.6, w: 3.6, h: 3.2 },
          { name: 'Bagno', x: 3.6, y: 4.6, w: 2.4, h: 3.2 },
          { name: 'Disimpegno', x: 6, y: 4.6, w: 3, h: 1.6 },
          { name: 'Studio', x: 6, y: 6.2, w: 3, h: 1.6 },
          { name: 'Bagno', x: 9, y: 4.6, w: 3.4, h: 3.2 },
        ],
      },
    ],
    publishedAt: '2026-09-15',
  },
  {
    slug: 'dorsoduro-giardino-san-trovaso',
    ref: 'IMM-DD-109',
    title: 'Piano rialzato con giardino a San Trovaso',
    zone: 'dorsoduro',
    microZone: 'San Trovaso',
    type: 'appartamento',
    availability: 'in-trattativa',
    price: 690_000,
    area: { commercial: 104, net: 88, outdoor: 60 },
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    floor: { label: 'Piano terra rialzato', level: 0, buildingFloors: 3, lift: false },
    entranceElevationCm: 138,
    energy: { class: 'E', ipe: 168 },
    heating: 'Autonomo a metano',
    built: 'XVII secolo',
    renovated: 2014,
    condition: 'buono',
    exposure: 'Sud sul giardino',
    listedBuilding: false,
    condoFees: 60,
    availableFrom: 'Libero al rogito',
    features: ['giardino'],
    hook: 'Un giardino di sessanta metri con il glicine, a due minuti dallo squero di San Trovaso.',
    summary:
      'Piano rialzato di 104 m² con giardino esclusivo di 60 m² esposto a sud. Due camere, due bagni, a San Trovaso.',
    description: [
      'Sei gradini dall’androne e si entra in un appartamento che vive sul giardino: il soggiorno e la cucina si aprono con due porte-finestre su sessanta metri di prato, un glicine centenario e un muro di mattoni che protegge dalla calle.',
      'Due camere, due bagni, un ingresso ampio con armadi a muro. La casa è stata sistemata nel 2014 ed è in buono stato.',
    ],
    whyWeLikeIt: [
      'Un giardino esposto a sud, nel cuore di Dorsoduro: per chi ha bambini o un cane vale più di qualsiasi vista.',
      'San Trovaso è silenziosa ma a due passi dalle Zattere e da Campo Santa Margherita.',
      'Nessuna scala da salire, eppure al riparo dall’acqua alta.',
    ],
    thingsToKnow: [
      {
        kind: 'acqua',
        title: 'Acqua alta',
        text: 'Piano rialzato a +175 cm, ingresso a +138 cm. Con maree eccezionali, sopra i 140 cm, il giardino può bagnarsi: il MOSE oggi le rende molto rare.',
      },
      {
        kind: 'costi',
        title: 'Il giardino',
        text: 'Uso esclusivo, proprietà condominiale: la manutenzione è a carico dell’appartamento.',
      },
      {
        kind: 'accesso',
        title: 'In trattativa',
        text: 'C’è una proposta in corso. Potete comunque visitarla: vi avvisiamo subito se la trattativa non va a buon fine.',
      },
    ],
    vaporetto: { stop: 'Zattere', lines: ['2', '5.1', '5.2'], minutes: 4 },
    proximity: [
      { label: 'Squero di San Trovaso', minutes: 2, mode: 'a piedi' },
      { label: 'Campo Santa Margherita', minutes: 6, mode: 'a piedi' },
      { label: 'Gallerie dell’Accademia', minutes: 6, mode: 'a piedi' },
      { label: 'Piazzale Roma', minutes: 16, mode: 'a piedi' },
    ],
    images: ['giardino-verde', 'soggiorno-quiete', 'cucina-isola', 'camera-lino', 'bagno-pietra'],
    plan: [
      {
        label: 'Piano rialzato',
        rooms: [
          { name: 'Soggiorno', x: 0, y: 0, w: 5.8, h: 4.4 },
          { name: 'Cucina', x: 5.8, y: 0, w: 3.2, h: 4.4 },
          { name: 'Camera', x: 9, y: 0, w: 3, h: 4.4 },
          { name: 'Camera', x: 0, y: 4.4, w: 3.6, h: 3 },
          { name: 'Bagno', x: 3.6, y: 4.4, w: 2.2, h: 3 },
          { name: 'Bagno', x: 5.8, y: 4.4, w: 2.2, h: 3 },
          { name: 'Ingresso', x: 8, y: 4.4, w: 4, h: 3 },
          { name: 'Giardino', x: 0, y: 7.4, w: 10, h: 6, outdoor: true },
        ],
      },
    ],
    publishedAt: '2026-07-22',
  },
  {
    slug: 'cannaregio-ultimo-piano-ormesini',
    ref: 'IMM-CN-110',
    title: 'Ultimo piano da ristrutturare agli Ormesini',
    zone: 'cannaregio',
    microZone: 'Ormesini',
    type: 'attico',
    availability: 'disponibile',
    price: 395_000,
    area: { commercial: 86, net: 74 },
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    floor: { label: 'Terzo e ultimo piano', level: 3, buildingFloors: 3, lift: false },
    entranceElevationCm: 130,
    energy: { class: 'F', ipe: 224 },
    heating: 'Autonomo a metano, caldaia da sostituire',
    built: 'XIX secolo',
    condition: 'da-ristrutturare',
    exposure: 'Est, ovest',
    listedBuilding: false,
    condoFees: 40,
    availableFrom: 'Libero al rogito',
    features: ['piano-alto', 'vista-canale'],
    hook: 'Da ristrutturare, sì. Ma con le travi, la luce da due lati e il rio sotto le finestre.',
    summary:
      'Ultimo piano di 86 m² da ristrutturare, doppia esposizione e affaccio sul rio della Misericordia, travi a vista.',
    description: [
      'Un ultimo piano che attraversa l’edificio da parte a parte: a est il rio, a ovest i tetti del Ghetto. Le travi originali sono in buone condizioni, i muri portanti permettono di ridisegnare la pianta quasi liberamente.',
      'Serve una ristrutturazione completa: impianti, bagno, cucina, serramenti. È l’occasione per costruirsi una casa su misura in una delle zone più vive di Cannaregio.',
    ],
    whyWeLikeIt: [
      'La doppia esposizione, in un ultimo piano, è quello che nessuna ristrutturazione può aggiungere dopo.',
      'Agli Ormesini si vive tutto l’anno: bacari, forni, vicini che si salutano.',
      'Il prezzo lascia margine per una ristrutturazione fatta bene.',
    ],
    thingsToKnow: [
      {
        kind: 'lavori',
        title: 'Ristrutturazione',
        text: 'Completa. Stima indicativa: 1.100–1.400 euro al m² a seconda delle finiture. Possiamo presentarvi due imprese con cui lavoriamo da anni.',
      },
      {
        kind: 'accesso',
        title: 'Scale',
        text: 'Tre rampe; nell’edificio non è possibile installare un ascensore.',
      },
      {
        kind: 'costi',
        title: 'Bonus edilizi',
        text: 'Le agevolazioni cambiano spesso: vanno verificate con un tecnico al momento dell’acquisto.',
      },
    ],
    vaporetto: { stop: 'Guglie', lines: ['4.1', '4.2', '5.1', '5.2'], minutes: 5 },
    proximity: [
      { label: 'Ghetto', minutes: 3, mode: 'a piedi' },
      { label: 'Fondamenta della Misericordia', minutes: 4, mode: 'a piedi' },
      { label: 'Supermercato', minutes: 5, mode: 'a piedi' },
      { label: 'Stazione ferroviaria', minutes: 10, mode: 'a piedi' },
    ],
    images: ['interno-arioso', 'interno-dettaglio', 'camera-calma', 'venezia-rio'],
    plan: [
      {
        label: 'Terzo piano',
        rooms: [
          { name: 'Soggiorno', x: 0, y: 0, w: 5, h: 4.2 },
          { name: 'Cucina', x: 5, y: 0, w: 2.8, h: 4.2 },
          { name: 'Camera', x: 7.8, y: 0, w: 3.2, h: 4.2 },
          { name: 'Camera', x: 0, y: 4.2, w: 3.4, h: 2.6 },
          { name: 'Bagno', x: 3.4, y: 4.2, w: 2.4, h: 2.6 },
          { name: 'Ingresso', x: 5.8, y: 4.2, w: 2, h: 2.6 },
          { name: 'Ripostiglio', x: 7.8, y: 4.2, w: 3.2, h: 2.6 },
        ],
      },
    ],
    publishedAt: '2026-09-24',
  },
  {
    slug: 'castello-quadrilocale-sant-elena',
    ref: 'IMM-CS-111',
    title: 'Quadrilocale nel verde di Sant’Elena',
    zone: 'castello',
    microZone: 'Sant’Elena',
    type: 'appartamento',
    availability: 'disponibile',
    price: 470_000,
    area: { commercial: 118, net: 102 },
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    floor: { label: 'Terzo piano', level: 3, buildingFloors: 4, lift: true },
    entranceElevationCm: 146,
    energy: { class: 'C', ipe: 96 },
    heating: 'Centralizzato con valvole termostatiche',
    built: '1930',
    renovated: 2020,
    condition: 'ristrutturato',
    exposure: 'Sud, ovest sul parco',
    listedBuilding: false,
    condoFees: 160,
    availableFrom: 'Libero da gennaio',
    features: ['ascensore', 'vista-laguna'],
    hook: 'Il parco sotto casa, la laguna in fondo al viale e l’ascensore: tre rarità veneziane insieme.',
    summary:
      'Quadrilocale di 118 m² al terzo piano con ascensore, tre camere e vista sul parco e sulla laguna. Ristrutturato nel 2020.',
    description: [
      'Sant’Elena è la Venezia che non ti aspetti: viali alberati, un grande parco, la laguna aperta. L’appartamento è al terzo piano di una palazzina degli anni Trenta con ascensore, e guarda il parco da un balcone a sud.',
      'Tre camere, due bagni, una cucina abitabile con finestra sulla laguna. Ristrutturato nel 2020 con impianti nuovi, è pronto da abitare.',
    ],
    whyWeLikeIt: [
      'Per una famiglia con bambini è difficile trovare di meglio nel centro storico.',
      'L’ascensore e le metrature regolari: una comodità quotidiana che a Venezia si paga cara altrove.',
      'Il Lido è a sette minuti di vaporetto: d’estate il mare è praticamente sotto casa.',
    ],
    thingsToKnow: [
      {
        kind: 'accesso',
        title: 'Distanze',
        text: 'Lontano dalla stazione: circa trenta minuti di vaporetto da Piazzale Roma.',
      },
      {
        kind: 'costi',
        title: 'Spese condominiali',
        text: '160 euro al mese, con il riscaldamento centralizzato incluso.',
      },
      {
        kind: 'acqua',
        title: 'Acqua alta',
        text: 'Ingresso a +146 cm: tra le quote più favorevoli del centro storico.',
      },
    ],
    vaporetto: { stop: 'Sant’Elena', lines: ['1', '4.1', '4.2', '5.1', '5.2'], minutes: 3 },
    proximity: [
      { label: 'Parco delle Rimembranze', minutes: 1, mode: 'a piedi' },
      { label: 'Scuola primaria', minutes: 6, mode: 'a piedi' },
      { label: 'Giardini della Biennale', minutes: 8, mode: 'a piedi' },
      { label: 'Lido', minutes: 7, mode: 'in vaporetto' },
    ],
    images: ['soggiorno-luce', 'cucina-isola', 'camera-lino', 'camera-calma', 'bagno-pietra', 'venezia-sera'],
    plan: [
      {
        label: 'Terzo piano',
        rooms: [
          { name: 'Soggiorno', x: 0, y: 0, w: 6, h: 4.8 },
          { name: 'Cucina', x: 6, y: 0, w: 3, h: 4.8 },
          { name: 'Camera', x: 9, y: 0, w: 3.6, h: 4.8 },
          { name: 'Camera', x: 0, y: 4.8, w: 3.4, h: 3.6 },
          { name: 'Camera', x: 3.4, y: 4.8, w: 3, h: 3.6 },
          { name: 'Bagno', x: 6.4, y: 4.8, w: 2.4, h: 3.6 },
          { name: 'Bagno', x: 8.8, y: 4.8, w: 2, h: 3.6 },
          { name: 'Ingresso', x: 10.8, y: 4.8, w: 1.8, h: 3.6 },
        ],
      },
    ],
    publishedAt: '2026-08-11',
  },
  {
    slug: 'san-marco-mansarda-altana-santo-stefano',
    ref: 'IMM-SM-112',
    title: 'Mansarda con altana vicino a Campo Santo Stefano',
    zone: 'san-marco',
    microZone: 'Santo Stefano',
    type: 'attico',
    availability: 'disponibile',
    price: 560_000,
    area: { commercial: 78, net: 64, outdoor: 12 },
    rooms: 3,
    bedrooms: 1,
    bathrooms: 1,
    floor: { label: 'Quarto piano, mansarda', level: 4, buildingFloors: 4, lift: false },
    entranceElevationCm: 112,
    energy: { class: 'E', ipe: 181 },
    heating: 'Autonomo a metano, split per il raffrescamento',
    built: 'XVI secolo',
    renovated: 2015,
    condition: 'ristrutturato',
    exposure: 'Sud, ovest',
    listedBuilding: true,
    condoFees: 85,
    availableFrom: 'Libero al rogito',
    features: ['altana', 'piano-alto'],
    hook: 'Quattro piani di scale, e poi i tetti di San Marco tutti per voi.',
    summary:
      'Mansarda di 78 m² con altana storica di 12 m² sui tetti di San Marco, a due passi da Campo Santo Stefano.',
    description: [
      'Sotto il tetto di un palazzo del Cinquecento, a due passi da Campo Santo Stefano: un soggiorno con cucina a vista, una camera, uno studio e un bagno, tutti con le travi del tetto in vista.',
      'Una scala in legno porta all’altana, dodici metri di tavolato da cui si vedono il campanile di Santo Stefano, la cupola della Salute e, nelle giornate limpide, le Dolomiti.',
    ],
    whyWeLikeIt: [
      'Un’altana in San Marco è un privilegio da poche famiglie.',
      'La posizione: il campo più elegante della città, la Fenice e l’Accademia a cinque minuti.',
      'Perfetta come casa per una persona o una coppia, o come pied-à-terre di grande carattere.',
    ],
    thingsToKnow: [
      {
        kind: 'accesso',
        title: 'Scale',
        text: 'Quattro rampe e nessun ascensore: è il prezzo del silenzio e della vista.',
      },
      {
        kind: 'vincoli',
        title: 'Altana storica',
        text: 'Edificio vincolato. Il legno dell’altana va ritrattato ogni cinque-sette anni, secondo le prescrizioni della Soprintendenza.',
      },
      {
        kind: 'acqua',
        title: 'Acqua alta',
        text: 'Ingresso a +112 cm: la calle si bagna con maree moderate. Il portone ha una paratia.',
      },
      {
        kind: 'impianti',
        title: 'D’estate',
        text: 'Il sottotetto è caldo nei mesi estivi: gli split sono già installati, ma il consumo va messo in conto.',
      },
    ],
    vaporetto: { stop: 'Sant’Angelo', lines: ['1'], minutes: 4 },
    proximity: [
      { label: 'Campo Santo Stefano', minutes: 2, mode: 'a piedi' },
      { label: 'Teatro La Fenice', minutes: 5, mode: 'a piedi' },
      { label: 'Gallerie dell’Accademia', minutes: 5, mode: 'a piedi' },
      { label: 'Rialto', minutes: 10, mode: 'a piedi' },
    ],
    images: ['soggiorno-quiete', 'interno-dettaglio', 'camera-lino', 'venezia-luce'],
    plan: [
      {
        label: 'Quarto piano',
        rooms: [
          { name: 'Soggiorno e cucina', x: 0, y: 0, w: 6, h: 4 },
          { name: 'Camera', x: 6, y: 0, w: 4.4, h: 4 },
          { name: 'Studio', x: 0, y: 4, w: 3.4, h: 2.4 },
          { name: 'Bagno', x: 3.4, y: 4, w: 2.6, h: 2.4 },
          { name: 'Ingresso', x: 6, y: 4, w: 4.4, h: 2.4 },
        ],
      },
      { label: 'Altana', rooms: [{ name: 'Altana', x: 0, y: 0, w: 4, h: 3, outdoor: true }] },
    ],
    publishedAt: '2026-09-27',
  },
]
